# Application
spring.application.name=forage

# ============================================
# DATABASE - PostgreSQL
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/forage
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# CONNECTION POOL - HikariCP
# ============================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.open-in-view=false
# ============================================
# THYMELEAF
# ============================================
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# ============================================
# SERVER
# ============================================
server.port=8086
server.error.include-message=always
server.error.include-stacktrace=on_param
